# Generated by Django 4.2.16 on 2025-07-07 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_identificacion', models.CharField(choices=[('cedula', 'Cédula'), ('ruc', 'RUC'), ('pasaporte', 'Pasaporte'), ('extranjero', 'Extranjero')], max_length=20)),
                ('identificacion', models.CharField(max_length=30, unique=True)),
                ('nombres_apellidos', models.CharField(max_length=150)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('M', 'Hombre'), ('F', 'Mujer')], max_length=1)),
                ('ocupacion', models.CharField(choices=[('estudiante', 'Estudiante'), ('docente', 'Docente')], max_length=20)),
                ('nivel_estudio', models.CharField(choices=[('prebasica', 'Prebásica 1-2'), ('basica', 'Básica 1-10'), ('bachillerato', 'Bachillerato 1-3'), ('universidad', 'Universidad/Superior')], max_length=20)),
                ('lugar_estudio_trabajo', models.CharField(max_length=150)),
                ('direccion', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('celular', models.CharField(max_length=15, unique=True)),
                ('telefono_convencional', models.CharField(blank=True, max_length=15, null=True)),
                ('parroquia', models.CharField(choices=[('el_valle', 'El Valle'), ('el_sagrario', 'El Sagrario'), ('san_sebastian', 'San Sebastián')], max_length=20)),
                ('programa_academico', models.CharField(choices=[('b2', 'B2 FIRST PREPARATION (FCE)'), ('teachers', 'PREPARATION FOR TEACHERS'), ('youth_intensive', 'YOUTH INTENSIVE PROGRAM'), ('youth', 'YOUTH PROGRAM'), ('seniors', 'SENIORS INTENSIVE PROGRAM'), ('express', 'English Express')], max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_estudiante', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emitir_factura_al_estudiante', models.BooleanField(default=False)),
                ('tipo_identificacion', models.CharField(choices=[('cedula', 'Cédula'), ('ruc', 'RUC'), ('pasaporte', 'Pasaporte'), ('extranjero', 'Extranjero')], max_length=20)),
                ('identificacion', models.CharField(max_length=30, unique=True)),
                ('razon_social', models.CharField(max_length=150)),
                ('direccion', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('celular', models.CharField(max_length=15, unique=True)),
                ('telefono_convencional', models.CharField(blank=True, max_length=15, null=True)),
                ('sexo', models.CharField(choices=[('M', 'Hombre'), ('F', 'Mujer')], max_length=1)),
                ('estado_civil', models.CharField(choices=[('soltero', 'Soltero'), ('casado', 'Casado'), ('divorciado', 'Divorciado'), ('viudo', 'Viudo')], max_length=20)),
                ('origen_ingresos', models.CharField(choices=[('empleado_publico', 'Empleado público'), ('empleado_privado', 'Empleado privado'), ('independiente', 'Independiente'), ('ama_de_casa', 'Ama de casa'), ('remesa', 'Remesa del exterior')], max_length=30)),
                ('parroquia', models.CharField(choices=[('el_valle', 'El Valle'), ('el_sagrario', 'El Sagrario'), ('san_sebastian', 'San Sebastián')], max_length=20)),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='representante', to='mySql.estudiante')),
            ],
        ),
    ]
