# Generated by Django 4.2.16 on 2025-07-08 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySql', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoVerificacionEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254)),
                ('codigo', models.CharField(max_length=6)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('expiracion', models.DateTimeField()),
            ],
        ),
    ]
