# Generated by Django 4.2.16 on 2025-07-11 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mySql', '0002_codigoverificacionemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('programa', models.CharField(max_length=100)),
                ('periodo', models.CharField(max_length=50)),
                ('horario', models.CharField(max_length=50)),
                ('paralelo', models.CharField(max_length=10)),
                ('establecimiento', models.CharField(max_length=100)),
                ('cupos', models.PositiveIntegerField()),
                ('metodo_pago', models.CharField(choices=[('deposito', 'Depósito'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta (3 a 6 meses sin intereses)')], max_length=20)),
                ('cuotas_pagar', models.PositiveIntegerField()),
                ('medio_entero', models.CharField(choices=[('redes', 'Redes sociales'), ('web', 'Página Web'), ('asesores', 'Contacto con Asesores Comerciales'), ('oficina', 'Oficina'), ('radio', 'Radio'), ('ferias', 'Ferias y/o Eventos'), ('otros', 'Otros')], max_length=30)),
                ('fecha_matricula', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='mySql.estudiante')),
            ],
        ),
    ]
