# Generated by Django 4.2.16 on 2025-07-12 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mySql', '0003_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('programa_academico', models.CharField(choices=[('b2', 'B2 FIRST PREPARATION (FCE)'), ('teachers', 'PREPARATION FOR TEACHERS'), ('youth_intensive', 'YOUTH INTENSIVE PROGRAM'), ('youth', 'YOUTH PROGRAM'), ('seniors', 'SENIORS INTENSIVE PROGRAM'), ('express', 'English Express')], max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('periodo', models.CharField(max_length=50)),
                ('horario', models.CharField(max_length=100)),
                ('cupos_disponibles', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='cuotas_pagar',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='cupos',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='establecimiento',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='horario',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='paralelo',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='periodo',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='programa',
        ),
        migrations.AddField(
            model_name='matricula',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='costo_matricula',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matricula',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('completada', 'Completada'), ('inactiva', 'Inactiva'), ('abandonada', 'Abandonada'), ('pendiente_pago', 'Pendiente de Pago'), ('confirmada', 'Confirmada')], default='pendiente_pago', max_length=20),
        ),
        migrations.AddField(
            model_name='matricula',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='fecha_matricula',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='medio_entero',
            field=models.CharField(choices=[('redes_sociales', 'Redes Sociales'), ('pagina_web', 'Página Web'), ('referido', 'Referido'), ('otro', 'Otro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='metodo_pago',
            field=models.CharField(choices=[('deposito', 'Depósito'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta (3 a 6 meses sin intereses)')], max_length=50),
        ),
        migrations.AddField(
            model_name='matricula',
            name='componente_cursado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mySql.componente'),
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docente', models.CharField(max_length=255)),
                ('nota_final', models.DecimalField(decimal_places=2, max_digits=5)),
                ('inasistencias', models.PositiveIntegerField(default=0)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_asociadas', to='mySql.componente')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='mySql.estudiante')),
            ],
            options={
                'unique_together': {('estudiante', 'componente')},
            },
        ),
    ]
