# Generated by Django 4.2.16 on 2025-07-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySql', '0004_componente_remove_matricula_cuotas_pagar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='cuotas',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
