# Generated by Django 4.2.16 on 2025-07-12 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mySql', '0005_matricula_cuotas'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPagoMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(choices=[('deposito', 'Depósito'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta')], max_length=20)),
                ('numero_comprobante', models.CharField(blank=True, max_length=100, null=True)),
                ('banco_emisor', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_tarjeta', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_tarjeta', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mySql.componente')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mySql.estudiante')),
            ],
        ),
    ]
