# Generated by Django 4.2.16 on 2025-07-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySql', '0006_datospagomatricula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datospagomatricula',
            old_name='fecha_pago',
            new_name='fecha_registro',
        ),
        migrations.RenameField(
            model_name='datospagomatricula',
            old_name='banco_emisor',
            new_name='id_depositante',
        ),
        migrations.RenameField(
            model_name='datospagomatricula',
            old_name='numero_comprobante',
            new_name='referencia',
        ),
        migrations.AddField(
            model_name='datospagomatricula',
            name='cvv',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='datospagomatricula',
            name='fecha_deposito',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='datospagomatricula',
            name='monto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='datospagomatricula',
            name='vencimiento',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
