# Generated by Django 4.2.16 on 2025-07-18 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySql', '0009_asignaciontarea_entregatarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='docentes/perfil/'),
        ),
    ]
