# Generated by Django 4.2.16 on 2025-07-19 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mySql', '0010_docente_imagen_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionDocenteComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docentes_asignados', to='mySql.componente')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes_asignados', to='mySql.docente')),
            ],
            options={
                'unique_together': {('docente', 'componente')},
            },
        ),
    ]
