# Generated by Django 4.2.16 on 2025-07-19 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mySql', '0011_asignaciondocentecomponente'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionFinalTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_final', models.FloatField()),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_finales', to='mySql.estudiante')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_finales', to='mySql.asignaciontarea')),
            ],
            options={
                'verbose_name': 'Calificación final de tarea',
                'verbose_name_plural': 'Calificaciones finales de tareas',
                'unique_together': {('estudiante', 'tarea')},
            },
        ),
    ]
