# Generated by Django 4.2.16 on 2025-07-20 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mySql', '0012_calificacionfinaltarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('contenido', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('publicada', models.BooleanField(default=True)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios_asociados', to='mySql.componente')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to='mySql.docente')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenAnuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='anuncios/imagenes/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='mySql.anuncio')),
            ],
        ),
        migrations.CreateModel(
            name='ComentarioAnuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha_comentario', models.DateTimeField(auto_now_add=True)),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='mySql.anuncio')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mySql.estudiante')),
            ],
        ),
    ]
