# Generated by Django 4.2.16 on 2025-07-20 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mySql', '0013_anuncio_imagenanuncio_comentarioanuncio'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicacionNotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('componente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mySql.componente')),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_apellidos', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('celular', models.CharField(max_length=15, unique=True)),
                ('imagen_perfil', models.ImageField(blank=True, null=True, upload_to='administradores/perfil/')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
