# Generated by Django 4.2.16 on 2025-07-21 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mySql', '0014_publicacionnotas_administrador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_administrador', to=settings.AUTH_USER_MODEL),
        ),
    ]
