# Generated by Django 4.2.16 on 2025-07-23 01:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mySql', '0015_alter_administrador_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('nueva_tarea', 'Nueva tarea asignada'), ('cambio_fecha', 'Cambio en fecha de entrega'), ('calificacion', 'Calificación de intento')], max_length=20)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('descripcion', models.TextField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mySql.docente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mySql.entregatarea')),
                ('notificacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='mySql.notificacion')),
                ('tarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mySql.asignaciontarea')),
            ],
        ),
    ]
