name: lms_english_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  http: ^1.1.0
  flutter_secure_storage: ^9.0.0 
  get: ^4.6.6
  flutter_svg: ^2.0.10+1
  flutter:
    sdk: flutter
  provider: ^6.1.1

  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8
  mime: ^2.0.0
  intl: ^0.20.2
  file_picker: ^10.2.0
  url_launcher: ^6.3.2
  path_provider: ^2.1.1
  open_file: ^3.3.2
  webview_flutter: ^4.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/chica.png
    - lib/assets/images/gorro.png
    - lib/assets/icons/cur.png
    - lib/assets/icons/ho.png
    - lib/assets/icons/me.png
    - lib/assets/icons/re.png

